### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by ForgottenUmbrella** [reorr/mantablockscreen#7]
The AUR (Arch Linux) package is based on versioned releases, so the changes made to improve installation, plus other changes made since v0.3, aren't available until a new release is made.

**Comment by reorr** [comment]
I have create new release, but i'm not the maintainer of AUR package. So, we will have to wait for the maintainer to update the AUR package.

**Comment by ForgottenUmbrella** [comment]
Thank you.
